export const START_INCREMENT = "START_INCREMENT";
export const SUCCESS_INCREMENT = "SUCCESS_INCREMENT";

export const START_DECREMENT = "START_DECREMENT";
export const SUCCESS_DECREMENT = "SUCCESS_DECREMENT";