export const ADD_CART_START = "ADD_CART_START"
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS"
export const ADD_CART_ERROR= "ADD_CART_ERROR"

export const UPDATE_CART_START = "UPDATE_CART_START"
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS"
export const UPDATE_CART_ERROR= "UPDATE_CART_ERROR"

export const INCREMENT_CART_START = "INCREMENT_CART_START"
export const INCREMENT_CART_SUCCESS = "INCREMENT_CART_SUCCESS"
export const INCREMENT_CART_ERROR= "INCREMENT_CART_ERROR"

export const DECREMENT_CART_START = "DECREMENT_CART_START"
export const DECREMENT_CART_SUCCESS = "DECREMENT_CART_SUCCESS"
export const DECREMENT_CART_ERROR= "DECREMENT_CART_ERROR"

export const INPUT_CART_START = "INPUT_CART_START"
export const INPUT_CART_SUCCESS = "INPUT_CART_SUCCESS"
export const INPUT_CART_ERROR= "INPUT_CART_ERROR"

export const REMOVE_CART_START = "REMOVE_CART_START"
export const REMOVE_CART_SUCCESS = "REMOVE_CART_SUCCESS"
export const REMOVE_CART_ERROR= "REMOVE_CART_ERROR"
