export const ADD_CART_START = "ADD_CART_START"
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS"
export const ADD_CART_ERROR= "ADD_CART_ERROR"

export const UPDATE_CART_START = "UPDATE_CART_START"
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS"
export const UPDATE_CART_ERROR= "UPDATE_CART_ERROR"

export const REMOVE_CART_START = "REMOVE_CART_START"
export const REMOVE_CART_SUCCESS = "REMOVE_CART_SUCCESS"
export const REMOVE_CART_ERROR= "REMOVE_CART_ERROR"
