export const ADD_PRODUCT_START = "ADD_PRODUCT_START"
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_ERROR= "ADD_PRODUCT_ERROR"

export const UPDATE_PRODUCT_START = "UPDATE_PRODUCT_START"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_ERROR= "UPDATE_PRODUCT_ERROR"

export const REMOVE_PRODUCT_START = "REMOVE_PRODUCT_START"
export const REMOVE_PRODUCT_SUCCESS = "REMOVE_PRODUCT_SUCCESS"
export const REMOVE_PRODUCT_ERROR= "REMOVE_PRODUCT_ERROR"
