export const ADD_ROLE_START = "ADD_ROLE_START"
export const ADD_ROLE_SUCCESS = "ADD_ROLE_SUCCESS"
export const ADD_ROLE_ERROR= "ADD_ROLE_ERROR"

export const UPDATE_ROLE_START = "UPDATE_ROLE_START"
export const UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS"
export const UPDATE_ROLE_ERROR= "UPDATE_ROLE_ERROR"

export const REMOVE_ROLE_START = "REMOVE_ROLE_START"
export const REMOVE_ROLE_SUCCESS = "REMOVE_ROLE_SUCCESS"
export const REMOVE_ROLE_ERROR= "REMOVE_ROLE_ERROR"
